# Lineare algebra

In [21]:
import numpy as np

## Numerieke primitieven
### Scalairen
$$a = 5$$

In [22]:
a = np.array(5)
print(a)
print(a.dtype)
print(a.shape)
print(a.__class__.__name__)

5
int64
()
ndarray


$$a = 3.0$$

In [23]:
a = np.array(3.0)
print(a)
print(a.shape)
print(a.dtype)

3.0
()
float64


### Vectoren

$$
\pmb{a} = \begin{bmatrix}
5 \cr
8 \cr
12
\end{bmatrix}
$$

In [24]:
a = np.array([5, 8, 12])
print(a)
print(a.shape)

[ 5  8 12]
(3,)


Representatie als een kolom-vector (een matrix met 1 kolom):

In [25]:
a.reshape(3, 1)

array([[ 5],
       [ 8],
       [12]])

Representatie als een rij-vector (een matrix met 1 _rij_):

$$
\pmb{a}^T = \begin{bmatrix}
5 & 8 & 12
\end{bmatrix}
$$

In [26]:
a.reshape(1, 3)

array([[ 5,  8, 12]])

Transpositie terug naar kolom-vector:

In [ ]:
a.reshape(1, 3).T

array([ 5,  8, 12])

### Matrices

$$
\pmb{B} = \begin{bmatrix}
1.0 & 2.0 & 3.0 \cr
7.0 & 1.0 & 2.0
\end{bmatrix}
$$

In [28]:
b = np.array([[1.0, 2.0, 3.0], [7.0, 1.0, 2.0]])
print(f"b: {b}")
print(f"b shape: {b.shape}")

b: [[1. 2. 3.]
 [7. 1. 2.]]
b shape: (2, 3)


$$
\pmb{B}^T
$$

In [29]:
print(b.T)

[[1. 7.]
 [2. 1.]
 [3. 2.]]


### Tensors

$$
\pmb{C} = \begin{bmatrix}
\begin{bmatrix}
1.0 & 2.0 & 3.0 \cr
7.0 & 1.0 & 2.0
\end{bmatrix}, \cr
\begin{bmatrix}
5.0 & 1.0 & 3.0 \cr
2.0 & 9.0 & 6.0
\end{bmatrix}
\end{bmatrix}
$$

In [30]:
c = np.array([[[1.0, 2.0, 3.0], [7.0, 1.0, 2.0]], [[5.0, 1.0, 3.0], [2.0, 9.0, 6.0]]])
print(f"c: {c}")
print(f"c shape: {c.shape}")

c: [[[1. 2. 3.]
  [7. 1. 2.]]

 [[5. 1. 3.]
  [2. 9. 6.]]]
c shape: (2, 2, 3)


In [42]:
# Reshape the 3D array
c.reshape(3, 2, 2)

array([[[1., 2.],
        [3., 7.]],

       [[1., 2.],
        [5., 1.]],

       [[3., 2.],
        [9., 6.]]])

In [32]:
# 4D tensor with random values
rng = np.random.default_rng(12345)
d = rng.random((5, 3, 2, 3))
print(d)

[[[[0.22733602 0.31675834 0.79736546]
   [0.67625467 0.39110955 0.33281393]]

  [[0.59830875 0.18673419 0.67275604]
   [0.94180287 0.24824571 0.94888115]]

  [[0.66723745 0.09589794 0.44183967]
   [0.88647992 0.6974535  0.32647286]]]


 [[[0.73392816 0.22013496 0.08159457]
   [0.1598956  0.34010018 0.46519315]]

  [[0.26642103 0.8157764  0.19329439]
   [0.12946908 0.09166475 0.59856801]]

  [[0.8547419  0.60162124 0.93198836]
   [0.72478136 0.86055132 0.9293378 ]]]


 [[[0.54618601 0.93767296 0.49498794]
   [0.27377318 0.45177871 0.66503892]]

  [[0.33089093 0.90345401 0.25707418]
   [0.33982834 0.2588534  0.35544648]]

  [[0.00502233 0.62860454 0.28238271]
   [0.06808769 0.61682898 0.17632632]]]


 [[[0.30438839 0.44088681 0.15020234]
   [0.21792886 0.47433312 0.47636886]]

  [[0.25523235 0.29756527 0.27906712]
   [0.26057921 0.48276159 0.21197904]]

  [[0.4956306  0.24626133 0.83848265]
   [0.18013059 0.86215629 0.17829944]]]


 [[[0.75053133 0.6111204  0.20915503]
   [0.75987242 0.2

## Element-gewijse operaties  
$$
\pmb{a} = \begin{bmatrix}
5 \cr
8 \cr
12
\end{bmatrix}
$$
$$
\pmb{a} + 5
$$

In [33]:
print(f"a: {a}")
print(f"a+5: {a + 5}")

a: [ 5  8 12]
a+5: [10 13 17]


$$
\pmb{a} \times 5
$$

In [34]:
print(f"a x 5: {a * 5}")

a x 5: [25 40 60]


$$
\pmb{b} = \begin{bmatrix}
1 \cr
2 \cr
3
\end{bmatrix}
$$

$$
\pmb{a} + \pmb{b}
$$

In [35]:
b = np.array([1, 2, 3])
print(f"a + b: {a + b}")

a + b: [ 6 10 15]


Let op voor dimensies!

In [36]:
b = np.array([1, 2, 3, 4])
print(f"a + b: {a + b}")

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

$$
\pmb{a} \odot \pmb{b}
$$

In [ ]:
b = np.array([1, 2, 3])
print(f"a * b: {a * b}")

a * b: [ 5 16 36]


$$
\pmb{A} = \begin{bmatrix}
1 & 2 \cr
3 & 4 \cr
5 & 6
\end{bmatrix}
$$

$$
\pmb{A}+5
$$

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(f"A: {A}")
print(f"A + 5: {A + 5}")

A: [[1 2]
 [3 4]
 [5 6]]
A + 5: [[ 6  7]
 [ 8  9]
 [10 11]]


$$
\pmb{A} \times 5
$$

In [ ]:
print(f"A x 5: {A * 5}")

A x 5: [[ 5 10]
 [15 20]
 [25 30]]


$$
\pmb{B} = \begin{bmatrix}
5 & 3 \cr
3 & 1 \cr
9 & 0
\end{bmatrix}
$$

$$
\pmb{A}+\pmb{B}
$$

In [ ]:
B = np.array([[5, 3], [3, 1], [9, 0]])
print(f"A: {A}")
print(f"B: {B}")
print(f"A + B: {A + B}")

A: [[1 2]
 [3 4]
 [5 6]]
B: [[5 3]
 [3 1]
 [9 0]]
A + B: [[ 6  5]
 [ 6  5]
 [14  6]]


$$
\pmb{A} \odot \pmb{B}
$$

In [ ]:
print(f"A * B: {A * B}")

A * B: [[ 5  6]
 [ 9  4]
 [45  0]]


$$
\pmb{A}^T + \pmb{b}
$$

In [ ]:
print(f"A: {A}")
print(f"b: {b}")

A: [[1 2]
 [3 4]
 [5 6]]
b: [1 2 3]


In [ ]:
print(A + b)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
print(A.T + b)

[[2 5 8]
 [3 6 9]]


$$
\pmb{A}^T \odot \pmb{b}
$$

In [ ]:
print(A.T * b)

[[ 1  6 15]
 [ 2  8 18]]


In [ ]:
# Subtract two 4D tensors
d = rng.random((5, 3, 2, 3))
g = rng.random((5, 3, 2, 3))
print(f"(d - g).shape: {(d - g).shape}")

(d - g).shape: (5, 3, 2, 3)


In [ ]:
h = g.reshape((3, 3, 2, 5))
j = g.reshape((3, 3 * 2 * 5))

In [ ]:
print((d - h).shape)

ValueError: operands could not be broadcast together with shapes (5,3,2,3) (3,3,2,5) 

In [ ]:
print((d - j).shape)

ValueError: operands could not be broadcast together with shapes (5,3,2,3) (3,30) 

## _Dot_ product

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}7 & 3 & 2\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}2 & 8 & 1\end{bmatrix}^T \cr
\pmb{a}^T\pmb{b} &= \ldots
\end{aligned}
$$

In [ ]:
a = np.array([7, 3, 2])
b = np.array([2, 8, 1])
print(f"a: {a}")
print(f"b: {b}")
print(f"a'b: {np.dot(a, b)}")

a: [7 3 2]
b: [2 8 1]
a'b: 40


In [ ]:
print(f"a'b: {7 * 2 + 3 * 8 + 2 * 1}")

a'b: 40


$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}4.6 & 1.1 & 5.3 & 8.2 & 10.1\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}6.1 & 1.5 & 3.5 & 7.9 & 2.8\end{bmatrix}^T \cr
\pmb{a}^T\pmb{b} &= \ldots
\end{aligned}
$$

In [ ]:
a = np.array([4.6, 1.1, 5.3, 8.2, 10.1])
b = np.array([6.1, 1.5, 3.5, 7.9, 2.8])
print(f"a: {a}")
print(f"b: {b}")
print(f"a'b: {np.dot(a, b)}")

a: [ 4.6  1.1  5.3  8.2 10.1]
b: [6.1 1.5 3.5 7.9 2.8]
a'b: 141.32


$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}6 & 1 & 2 & 7\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}2 & 2 & 1\end{bmatrix}^T \cr
\pmb{a}^T\pmb{b} &= \ldots
\end{aligned}
$$

In [ ]:
a = np.array([6, 1, 2, 7])
b = np.array([2, 2, 1])
print(f"a: {a}")
print(f"b: {b}")
print(f"a'b: {np.dot(a, b)}")

a: [6 1 2 7]
b: [2 2 1]


ValueError: shapes (4,) and (3,) not aligned: 4 (dim 0) != 3 (dim 0)

$$
\begin{aligned}
\pmb{A} &=
\begin{bmatrix}
3 & 3 & 2 & 7 \cr
1 & 4 & 7 & 5 \cr
9 & 2 & 8 & 3
\end{bmatrix} \cr
\pmb{b} &= \begin{bmatrix}4 & 2 & 8 & 1\end{bmatrix}^T \cr
\pmb{A}\pmb{b} &= \ldots
\end{aligned}
$$

In [ ]:
A = np.array([[3, 3, 2, 7], [1, 4, 7, 5], [9, 2, 8, 3]])
b = np.array([4, 2, 8, 1])
print(f"A: {A}")
print(f"b: {b}")
print(f"Ab: {np.dot(A, b)}")

A: [[3 3 2 7]
 [1 4 7 5]
 [9 2 8 3]]
b: [4 2 8 1]
Ab: [ 41  73 107]


In [ ]:
# Mind the order!
print(f"bA: {np.dot(b, A)}")

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

$$
\begin{aligned}
\pmb{A} &=
\begin{bmatrix}
6.1 & 3.7 \cr
1.0 & 4.3 \cr
5.1 & 3.3 \cr
3.9 & 3.7 \cr
7.9 & 8.2 \cr
\end{bmatrix} \cr
\pmb{b} &= \begin{bmatrix}3.0 & 2.2\end{bmatrix}^T \cr
\pmb{A}\pmb{b} &= \ldots
\end{aligned}
$$

In [ ]:
A = np.array([[6.1, 3.7], [1.0, 4.3], [5.1, 3.3], [3.9, 3.7], [7.9, 8.2]])
b = np.array([3.0, 2.2])
print(f"A: {A}")
print(f"b: {b}")
print(f"Ab: {np.dot(A, b)}")

A: [[6.1 3.7]
 [1.  4.3]
 [5.1 3.3]
 [3.9 3.7]
 [7.9 8.2]]
b: [3.  2.2]
Ab: [26.44 12.46 22.56 19.84 41.74]


$$
\begin{aligned}
\pmb{A} &=
\begin{bmatrix}
3 & 3 & 2 & 7 \cr
1 & 4 & 7 & 5 \cr
9 & 2 & 8 & 3
\end{bmatrix} \cr
\pmb{B} &=
\begin{bmatrix}
6 & 2 \cr
1 & 7 \cr
2 & 2 \cr
7 & 5
\end{bmatrix} \cr
\pmb{A}\pmb{B} &= \ldots
\end{aligned}
$$

In [ ]:
A = np.array([[3, 3, 2, 7], [1, 4, 7, 5], [9, 2, 8, 3]])
B = np.array(
    [
        [6, 2],
        [1, 7],
        [2, 2],
        [7, 5],
    ]
)
print(f"A: {A}")
print(f"B: {B}")
print(f"AB: {np.dot(A, B)}")

A: [[3 3 2 7]
 [1 4 7 5]
 [9 2 8 3]]
B: [[6 2]
 [1 7]
 [2 2]
 [7 5]]
AB: [[74 66]
 [59 69]
 [93 63]]


In [ ]:
# Mind the order!
print(f"BA: {np.dot(B, A)}")

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

Bereken het gemiddelde van de reeks $0$ tot en met $113$ aan de hand van een _dot_ product.

In [ ]:
n = 114
a = np.arange(n)
print(f"a: {a[:10]} ...")
w = np.ones((n,))
w /= n
print(f"w: {w[:10]} ...")
print(f"a'w: {np.dot(a, w)}")

a: [0 1 2 3 4 5 6 7 8 9] ...
w: [0.00877193 0.00877193 0.00877193 0.00877193 0.00877193 0.00877193
 0.00877193 0.00877193 0.00877193 0.00877193] ...
a'w: 56.5


$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}5 & 3 & 2 & 9 & 2\end{bmatrix}^T \cr
||\pmb{a}||_2 &= \ldots
\end{aligned} 
$$

In [ ]:
a = np.array([5, 3, 2, 9, 2])
print(f"||a||: {np.sqrt(np.dot(a, a))}")

||a||: 11.090536506409418


In [ ]:
# Built-in L2 norm function
print(f"||a||: {np.linalg.norm(a)}")

||a||: 11.090536506409418


Hoe groot is de cosine similarity tussen:

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}4.6 & 1.1 & 5.3 & 8.2 & 10.1\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}6.1 & 1.5 & 3.5 & 7.9 & 2.8\end{bmatrix}^T \cr
\end{aligned}
$$

In [ ]:
a = np.array([4.6, 1.1, 5.3, 8.2, 10.1])
b = np.array([6.1, 1.5, 3.5, 7.9, 2.8])
a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b)
print(f"cos(theta): {np.dot(a, b) / (a_norm * b_norm)}")

cos(theta): 0.8633164353920106


## Speciale matrices

Maak een diagonale matrix:

$$
diag(3.3, 6.0, 7.1, 5.4)
$$

In [ ]:
np.diag([3.3, 6.0, 7.1, 5.4])

array([[3.3, 0. , 0. , 0. ],
       [0. , 6. , 0. , 0. ],
       [0. , 0. , 7.1, 0. ],
       [0. , 0. , 0. , 5.4]])

Maak een idenditeitsmatrix:

$$
\pmb{I}_{67}
$$

In [ ]:
np.identity(67)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(67, 67))

Transformeer de volgende matrix in (a) een _upper triangular matrix_ en (b) een _lower triangular matrix_:

$$
\begin{bmatrix}
3 & 3 & 2 & 7 \cr
1 & 4 & 7 & 5 \cr
8 & 5 & 5 & 2 \cr
9 & 2 & 8 & 3
\end{bmatrix}
$$

In [ ]:
X = np.array([[3, 3, 2, 7], [1, 4, 7, 5], [8, 5, 5, 2], [9, 2, 8, 3]])

np.triu(X)

array([[3, 3, 2, 7],
       [0, 4, 7, 5],
       [0, 0, 5, 2],
       [0, 0, 0, 3]])

In [ ]:
np.tril(X)

array([[3, 0, 0, 0],
       [1, 4, 0, 0],
       [8, 5, 5, 0],
       [9, 2, 8, 3]])

Ga na of deze matrix (a) een orthogonale matrix is en (b) een rotatiematrix is.
$$
\pmb{A} =
\begin{bmatrix}
0.70710678 & -0.70710678 & 0.0 & 0.0 \cr
0.70710678 & 0.70710678 & 0.0 & 0.0 \cr
0.0 & 0.0 & 1.0 & 0.0 \cr
0.0 & 0.0 & 0.0 & 1.0
\end{bmatrix}
$$

In [ ]:
X = np.array(
    [
        [0.70710678, -0.70710678, 0.0, 0.0],
        [0.70710678, 0.70710678, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
    ]
)

# a) Check orthogonality
XTX = X.T @ X
ortho = np.all(np.round(XTX) == np.identity(X.shape[0]))
print(f"Orthogonality: {ortho}")

# b) Check rotation matrix
rot = np.linalg.det(X).round() == 1.0
print(f"Rotation matrix: {ortho and rot}")

Orthogonality: True
Rotation matrix: True


## Systeem van lineaire vergelijkingen

Gegeven het volgende stelsel:

$$
\begin{align}
14 &= 2\beta_1 + \beta_2 + 3\beta_3 \cr
18 &= \beta_1 + 4\beta_2 + 2\beta_3 \cr
12 &= 3\beta_1 + 2\beta_2 + \beta_3 \cr
\end{align}
$$

wat is de oplossing voor $\beta_1$, $\beta_2$ en $\beta_3$?


1. Matrix notatie

$$\mathbf{y} = \begin{bmatrix} 14 \\ 18 \\ 12 \end{bmatrix}, \quad \mathbf{X} = \begin{bmatrix} 2 & 1 & 3 \\ 1 & 4 & 2 \\ 3 & 2 & 1 \end{bmatrix}, \quad \mathbf{b} = \begin{bmatrix} \beta_1 \\ \beta_2 \\ \beta_3 \end{bmatrix}$$

In [ ]:
y = np.array([14, 18, 12])
X = np.array([[2, 1, 3], [1, 4, 2], [3, 2, 1]])

2. Inverse van $\pmb{X}$

$$
\mathbf{X}^{-1} = \frac{1}{det(\pmb{X})}
\begin{bmatrix}
(x_{22}x_{33} - x_{23}x_{32}) & -(x_{12}x_{33} - x_{13}x_{32}) & (x_{12}x_{23} - x_{13}x_{22}) \cr
-(x_{21}x_{33} - x_{23}x_{31}) & (x_{11}x_{33} - x_{13}x_{31}) & -(x_{11}x_{23} - x_{13}x_{21}) \cr
(x_{21}x_{32} - x_{22}x_{31}) & -(x_{11}x_{32} - x_{12}x_{31}) & (x_{11}x_{22} - x_{12}x_{21})
\end{bmatrix}
$$


$$
\begin{align}
\det(\mathbf{X}) &= 2(4 \cdot 1 - 2 \cdot 2) - 1(1 \cdot 1 - 2 \cdot 3) + 3(1 \cdot 2 - 4 \cdot 3) \cr
&= 2(4 - 4) - 1(1 - 6) + 3(2 - 12) = 0 + 5 - 30 = -25
\end{align}
$$
  
$$
\begin{align}
\mathbf{X}^{-1} &= \frac{1}{-25} \begin{bmatrix} 0 & 5 & -10 \\ 5 & -7 & -1 \\ -10 & -1 & 7 \end{bmatrix} \cr
&= \begin{bmatrix} 0 & -0.2 & 0.4 \\ -0.2 & 0.28 & 0.04 \\ 0.4 & 0.04 & -0.28 \end{bmatrix}
\end{align}
$$

In [ ]:
# Determinant of X
det = np.linalg.det(X)
print(f"det(X) = {det.round()}")

# Inverse of X
inv = np.linalg.inv(X)
print(f"X-1 = {inv}")

det(X) = -25.0
X-1 = [[ 0.   -0.2   0.4 ]
 [-0.2   0.28  0.04]
 [ 0.4   0.04 -0.28]]


3. Oplossing

$$
\pmb{b} = \pmb{X}^{-1}\pmb{y}
$$

In [ ]:
b = np.dot(inv, y)
print(f"b: {b}")

# Verification
print(f"y: {y}")
print(f"Xb: {np.dot(X, b)}")

b: [1.2  2.72 2.96]
y: [14 18 12]
Xb: [14. 18. 12.]
